#!/bin/sh
# Regenerate the real third-party `pylock.toml` documents in this directory.
#
# These are the only documents in the differential corpus that this repository did
# not write. `uv` has its own reading of PEP 751, so a document it writes is an
# input from outside this project; the corpus records them as accepted and the
# library has to keep accepting them.
#
# They are committed, not regenerated by the build, for the same reason the real
# `METADATA` documents are: a newer `uv` would silently change what the corpus
# covers. Re-running this script is a deliberate act, and the provenance file has
# to be updated with it.
#
# Usage (from the repository root):
#
#   sh pylock_cases/uv/regenerate.sh
#
# Requires `uv` on PATH and network access to an index. It runs against the
# Tsinghua mirror because pypi.org is not reachable from the machine this corpus
# was produced on; the index a file came from is recorded inside the document
# itself, in each package's `index` member.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

export UV_DEFAULT_INDEX=https://pypi.tuna.tsinghua.edu.cn/simple

# project name -> dependency requirement
set -- \
  "flask:flask>=3.0" \
  "requests:requests" \
  "numpy:numpy" \
  "django:django>=4.2" \
  "httpx:httpx[http2]" \
  "cattrs:cattrs"

for spec in "$@"; do
  name=${spec%%:*}
  dep=${spec#*:}
  mkdir -p "$work/$name"
  cd "$work/$name"
  cat > pyproject.toml <<EOF
[project]
name = "$name-probe"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["$dep"]
EOF
  uv export --format pylock.toml > "$here/$name.toml"
  rm -rf "$work/$name"
done

echo "wrote:"
wc -l "$here"/*.toml
echo
echo "now update $here/provenance.txt with the uv version, then regenerate the"
echo "fixture: python3 -B tools/fetch_pylock_corpus.py"
